//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://iec.ch/TC57/2011/DERGroupDispatchMessage", ClrNamespace="iec.ch.TC57._2011.DERGroupDispatchMessage")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://iec.ch/TC57/2011/schema/message", ClrNamespace="iec.ch.TC57._2011.schema.message")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://iec.ch/TC57/2011/RequestDERGroupDispatch", ConfigurationName="DERGroupDispatch_Port")]
public interface DERGroupDispatch_Port
{
    
    // CODEGEN: Generating message contract since the operation CreateDERGroupDispatch is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://iec.ch/TC57/2011/DERGroupDispatch/CreateDERGroupDispatch", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(iec.ch.TC57._2011.DERGroupDispatchMessage.DERGroupDispatchFaultMessageType), Action="http://iec.ch/TC57/2011/DERGroupDispatch/CreateDERGroupDispatch", Name="DERGroupDispatchFaultMessage", Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    CreateDERGroupDispatchResponse CreateDERGroupDispatch(CreateDERGroupDispatchRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://iec.ch/TC57/2011/DERGroupDispatch/CreateDERGroupDispatch", ReplyAction="*")]
    System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> CreateDERGroupDispatchAsync(CreateDERGroupDispatchRequest request);
    
    // CODEGEN: Generating message contract since the operation ChangeDERGroupDispatch is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://iec.ch/TC57/2011/DERGroupDispatch/ChangeDERGroupDispatch", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(iec.ch.TC57._2011.DERGroupDispatchMessage.DERGroupDispatchFaultMessageType), Action="http://iec.ch/TC57/2011/DERGroupDispatch/ChangeDERGroupDispatch", Name="DERGroupDispatchFaultMessage", Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    CreateDERGroupDispatchResponse ChangeDERGroupDispatch(ChangeDERGroupDispatchRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://iec.ch/TC57/2011/DERGroupDispatch/ChangeDERGroupDispatch", ReplyAction="*")]
    System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> ChangeDERGroupDispatchAsync(ChangeDERGroupDispatchRequest request);
    
    // CODEGEN: Generating message contract since the operation CancelDERGroupDispatch is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://iec.ch/TC57/2011/DERGroupDispatch/CancelDERGroupDispatch", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(iec.ch.TC57._2011.DERGroupDispatchMessage.DERGroupDispatchFaultMessageType), Action="http://iec.ch/TC57/2011/DERGroupDispatch/CancelDERGroupDispatch", Name="DERGroupDispatchFaultMessage", Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    CreateDERGroupDispatchResponse CancelDERGroupDispatch(CancelDERGroupDispatchRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://iec.ch/TC57/2011/DERGroupDispatch/CancelDERGroupDispatch", ReplyAction="*")]
    System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> CancelDERGroupDispatchAsync(CancelDERGroupDispatchRequest request);
    
    // CODEGEN: Generating message contract since the operation CloseDERGroupDispatch is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://iec.ch/TC57/2011/DERGroupDispatch/CloseDERGroupDispatch", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(iec.ch.TC57._2011.DERGroupDispatchMessage.DERGroupDispatchFaultMessageType), Action="http://iec.ch/TC57/2011/DERGroupDispatch/CloseDERGroupDispatch", Name="DERGroupDispatchFaultMessage", Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    CreateDERGroupDispatchResponse CloseDERGroupDispatch(CloseDERGroupDispatchRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://iec.ch/TC57/2011/DERGroupDispatch/CloseDERGroupDispatch", ReplyAction="*")]
    System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> CloseDERGroupDispatchAsync(CloseDERGroupDispatchRequest request);
    
    // CODEGEN: Generating message contract since the operation DeleteDERGroupDispatch is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://iec.ch/TC57/2011/DERGroupDispatch/DeleteDERGroupDispatch", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(iec.ch.TC57._2011.DERGroupDispatchMessage.DERGroupDispatchFaultMessageType), Action="http://iec.ch/TC57/2011/DERGroupDispatch/DeleteDERGroupDispatch", Name="DERGroupDispatchFaultMessage", Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    CreateDERGroupDispatchResponse DeleteDERGroupDispatch(DeleteDERGroupDispatchRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://iec.ch/TC57/2011/DERGroupDispatch/DeleteDERGroupDispatch", ReplyAction="*")]
    System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> DeleteDERGroupDispatchAsync(DeleteDERGroupDispatchRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage")]
public partial class DERGroupDispatchRequestMessageType
{
    
    private HeaderType headerField;
    
    private RequestType requestField;
    
    private DERGroupDispatchPayloadType payloadField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public HeaderType Header
    {
        get
        {
            return this.headerField;
        }
        set
        {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public RequestType Request
    {
        get
        {
            return this.requestField;
        }
        set
        {
            this.requestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public DERGroupDispatchPayloadType Payload
    {
        get
        {
            return this.payloadField;
        }
        set
        {
            this.payloadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class HeaderType
{
    
    private HeaderTypeVerb verbField;
    
    private string nounField;
    
    private string revisionField;
    
    private ReplayDetectionType replayDetectionField;
    
    private string contextField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string sourceField;
    
    private bool asyncReplyFlagField;
    
    private bool asyncReplyFlagFieldSpecified;
    
    private string replyAddressField;
    
    private bool ackRequiredField;
    
    private bool ackRequiredFieldSpecified;
    
    private UserType userField;
    
    private string messageIDField;
    
    private string correlationIDField;
    
    private string commentField;
    
    private MessageProperty[] propertyField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public HeaderTypeVerb Verb
    {
        get
        {
            return this.verbField;
        }
        set
        {
            this.verbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Noun
    {
        get
        {
            return this.nounField;
        }
        set
        {
            this.nounField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Revision
    {
        get
        {
            return this.revisionField;
        }
        set
        {
            this.revisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public ReplayDetectionType ReplayDetection
    {
        get
        {
            return this.replayDetectionField;
        }
        set
        {
            this.replayDetectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string Context
    {
        get
        {
            return this.contextField;
        }
        set
        {
            this.contextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public System.DateTime Timestamp
    {
        get
        {
            return this.timestampField;
        }
        set
        {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified
    {
        get
        {
            return this.timestampFieldSpecified;
        }
        set
        {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string Source
    {
        get
        {
            return this.sourceField;
        }
        set
        {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public bool AsyncReplyFlag
    {
        get
        {
            return this.asyncReplyFlagField;
        }
        set
        {
            this.asyncReplyFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AsyncReplyFlagSpecified
    {
        get
        {
            return this.asyncReplyFlagFieldSpecified;
        }
        set
        {
            this.asyncReplyFlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string ReplyAddress
    {
        get
        {
            return this.replyAddressField;
        }
        set
        {
            this.replyAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public bool AckRequired
    {
        get
        {
            return this.ackRequiredField;
        }
        set
        {
            this.ackRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AckRequiredSpecified
    {
        get
        {
            return this.ackRequiredFieldSpecified;
        }
        set
        {
            this.ackRequiredFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public UserType User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public string MessageID
    {
        get
        {
            return this.messageIDField;
        }
        set
        {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public string CorrelationID
    {
        get
        {
            return this.correlationIDField;
        }
        set
        {
            this.correlationIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=13)]
    public string Comment
    {
        get
        {
            return this.commentField;
        }
        set
        {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Property", Order=14)]
    public MessageProperty[] Property
    {
        get
        {
            return this.propertyField;
        }
        set
        {
            this.propertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=15)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/schema/message")]
public enum HeaderTypeVerb
{
    
    /// <remarks/>
    cancel,
    
    /// <remarks/>
    canceled,
    
    /// <remarks/>
    change,
    
    /// <remarks/>
    changed,
    
    /// <remarks/>
    create,
    
    /// <remarks/>
    created,
    
    /// <remarks/>
    close,
    
    /// <remarks/>
    closed,
    
    /// <remarks/>
    delete,
    
    /// <remarks/>
    deleted,
    
    /// <remarks/>
    get,
    
    /// <remarks/>
    reply,
    
    /// <remarks/>
    execute,
    
    /// <remarks/>
    executed,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class ReplayDetectionType
{
    
    private string nonceField;
    
    private System.DateTime createdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Nonce
    {
        get
        {
            return this.nonceField;
        }
        set
        {
            this.nonceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public System.DateTime Created
    {
        get
        {
            return this.createdField;
        }
        set
        {
            this.createdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="NameTypeAuthority", Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class NameTypeAuthority1
{
    
    private string nameField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="NameType", Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class NameType1
{
    
    private string nameField;
    
    private string descriptionField;
    
    private NameTypeAuthority1 nameTypeAuthorityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public NameTypeAuthority1 NameTypeAuthority
    {
        get
        {
            return this.nameTypeAuthorityField;
        }
        set
        {
            this.nameTypeAuthorityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Name", Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class Name1
{
    
    private string nameField;
    
    private NameType1 nameTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public NameType1 NameType
    {
        get
        {
            return this.nameTypeField;
        }
        set
        {
            this.nameTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class ObjectType
{
    
    private string mRIDField;
    
    private Name1[] nameField;
    
    private string objectTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string mRID
    {
        get
        {
            return this.mRIDField;
        }
        set
        {
            this.mRIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Name", Order=1)]
    public Name1[] Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string objectType
    {
        get
        {
            return this.objectTypeField;
        }
        set
        {
            this.objectTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class LocationType
{
    
    private string nodeField;
    
    private string pipelineField;
    
    private string stageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string node
    {
        get
        {
            return this.nodeField;
        }
        set
        {
            this.nodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string pipeline
    {
        get
        {
            return this.pipelineField;
        }
        set
        {
            this.pipelineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string stage
    {
        get
        {
            return this.stageField;
        }
        set
        {
            this.stageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class ErrorType
{
    
    private string codeField;
    
    private ErrorTypeLevel levelField;
    
    private bool levelFieldSpecified;
    
    private string reasonField;
    
    private string detailsField;
    
    private System.Xml.XmlQualifiedName xpathField;
    
    private string stackTraceField;
    
    private LocationType locationField;
    
    private ErrorTypeID idField;
    
    private ErrorTypeRelatedID relatedIDField;
    
    private ObjectType objectField;
    
    private string operationIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ErrorTypeLevel level
    {
        get
        {
            return this.levelField;
        }
        set
        {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool levelSpecified
    {
        get
        {
            return this.levelFieldSpecified;
        }
        set
        {
            this.levelFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string reason
    {
        get
        {
            return this.reasonField;
        }
        set
        {
            this.reasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string details
    {
        get
        {
            return this.detailsField;
        }
        set
        {
            this.detailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public System.Xml.XmlQualifiedName xpath
    {
        get
        {
            return this.xpathField;
        }
        set
        {
            this.xpathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string stackTrace
    {
        get
        {
            return this.stackTraceField;
        }
        set
        {
            this.stackTraceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public LocationType Location
    {
        get
        {
            return this.locationField;
        }
        set
        {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public ErrorTypeID ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public ErrorTypeRelatedID relatedID
    {
        get
        {
            return this.relatedIDField;
        }
        set
        {
            this.relatedIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public ObjectType @object
    {
        get
        {
            return this.objectField;
        }
        set
        {
            this.objectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=10)]
    public string operationId
    {
        get
        {
            return this.operationIdField;
        }
        set
        {
            this.operationIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/schema/message")]
public enum ErrorTypeLevel
{
    
    /// <remarks/>
    INFORM,
    
    /// <remarks/>
    WARNING,
    
    /// <remarks/>
    FATAL,
    
    /// <remarks/>
    CATASTROPHIC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class ErrorTypeID
{
    
    private string idTypeField;
    
    private string idAuthorityField;
    
    private IDKindType kindField;
    
    private bool kindFieldSpecified;
    
    private string objectTypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idType
    {
        get
        {
            return this.idTypeField;
        }
        set
        {
            this.idTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idAuthority
    {
        get
        {
            return this.idAuthorityField;
        }
        set
        {
            this.idAuthorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public IDKindType kind
    {
        get
        {
            return this.kindField;
        }
        set
        {
            this.kindField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool kindSpecified
    {
        get
        {
            return this.kindFieldSpecified;
        }
        set
        {
            this.kindFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string objectType
    {
        get
        {
            return this.objectTypeField;
        }
        set
        {
            this.objectTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/schema/message")]
public enum IDKindType
{
    
    /// <remarks/>
    name,
    
    /// <remarks/>
    uuid,
    
    /// <remarks/>
    transaction,
    
    /// <remarks/>
    other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class ErrorTypeRelatedID
{
    
    private string idTypeField;
    
    private string idAuthorityField;
    
    private IDKindType kindField;
    
    private bool kindFieldSpecified;
    
    private string objectTypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idType
    {
        get
        {
            return this.idTypeField;
        }
        set
        {
            this.idTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idAuthority
    {
        get
        {
            return this.idAuthorityField;
        }
        set
        {
            this.idAuthorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public IDKindType kind
    {
        get
        {
            return this.kindField;
        }
        set
        {
            this.kindField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool kindSpecified
    {
        get
        {
            return this.kindFieldSpecified;
        }
        set
        {
            this.kindFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string objectType
    {
        get
        {
            return this.objectTypeField;
        }
        set
        {
            this.objectTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class ReplyType
{
    
    private ReplyTypeResult resultField;
    
    private ErrorType[] errorField;
    
    private ReplyTypeID[] idField;
    
    private System.Xml.XmlElement[] anyField;
    
    private string operationIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ReplyTypeResult Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Error", Order=1)]
    public ErrorType[] Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ID", Order=2)]
    public ReplyTypeID[] ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
    public string operationId
    {
        get
        {
            return this.operationIdField;
        }
        set
        {
            this.operationIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/schema/message")]
public enum ReplyTypeResult
{
    
    /// <remarks/>
    OK,
    
    /// <remarks/>
    PARTIAL,
    
    /// <remarks/>
    FAILED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class ReplyTypeID
{
    
    private string idTypeField;
    
    private string idAuthorityField;
    
    private IDKindType kindField;
    
    private bool kindFieldSpecified;
    
    private string objectTypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idType
    {
        get
        {
            return this.idTypeField;
        }
        set
        {
            this.idTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idAuthority
    {
        get
        {
            return this.idAuthorityField;
        }
        set
        {
            this.idAuthorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public IDKindType kind
    {
        get
        {
            return this.kindField;
        }
        set
        {
            this.kindField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool kindSpecified
    {
        get
        {
            return this.kindFieldSpecified;
        }
        set
        {
            this.kindFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string objectType
    {
        get
        {
            return this.objectTypeField;
        }
        set
        {
            this.objectTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage")]
public partial class DERGroupDispatchResponseMessageType
{
    
    private HeaderType headerField;
    
    private ReplyType replyField;
    
    private DERGroupDispatchPayloadType payloadField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public HeaderType Header
    {
        get
        {
            return this.headerField;
        }
        set
        {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ReplyType Reply
    {
        get
        {
            return this.replyField;
        }
        set
        {
            this.replyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public DERGroupDispatchPayloadType Payload
    {
        get
        {
            return this.payloadField;
        }
        set
        {
            this.payloadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage")]
public partial class DERGroupDispatchPayloadType
{
    
    private DERGroupDispatch[] dERGroupDispatchesField;
    
    private OperationSet operationSetField;
    
    private string compressedField;
    
    private string formatField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.epri.com/2013/DERGroupDispatch#", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public DERGroupDispatch[] DERGroupDispatches
    {
        get
        {
            return this.dERGroupDispatchesField;
        }
        set
        {
            this.dERGroupDispatchesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public OperationSet OperationSet
    {
        get
        {
            return this.operationSetField;
        }
        set
        {
            this.operationSetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Compressed
    {
        get
        {
            return this.compressedField;
        }
        set
        {
            this.compressedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Format
    {
        get
        {
            return this.formatField;
        }
        set
        {
            this.formatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.epri.com/2013/DERGroupDispatch#")]
public partial class DERGroupDispatch
{
    
    private DERGroup dERGroupField;
    
    private RequestedCapability requestedCapabilityField;
    
    private extensionsItem[] extensionsListField;
    
    private Name[] namesField;
    
    private string mRIDField;
    
    private otherCapability otherCapabilityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public DERGroup DERGroup
    {
        get
        {
            return this.dERGroupField;
        }
        set
        {
            this.dERGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public RequestedCapability RequestedCapability
    {
        get
        {
            return this.requestedCapabilityField;
        }
        set
        {
            this.requestedCapabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public extensionsItem[] extensionsList
    {
        get
        {
            return this.extensionsListField;
        }
        set
        {
            this.extensionsListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Names", Order=3)]
    public Name[] Names
    {
        get
        {
            return this.namesField;
        }
        set
        {
            this.namesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string mRID
    {
        get
        {
            return this.mRIDField;
        }
        set
        {
            this.mRIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public otherCapability otherCapability
    {
        get
        {
            return this.otherCapabilityField;
        }
        set
        {
            this.otherCapabilityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.epri.com/2013/DERGroupDispatch#")]
public partial class DERGroup
{
    
    private string nameField;
    
    private string mRIDField;
    
    private Name[] namesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string mRID
    {
        get
        {
            return this.mRIDField;
        }
        set
        {
            this.mRIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Names", Order=2)]
    public Name[] Names
    {
        get
        {
            return this.namesField;
        }
        set
        {
            this.namesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.epri.com/2013/DERGroupDispatch#")]
public partial class Name
{
    
    private string nameField;
    
    private NameType nameTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public NameType NameType
    {
        get
        {
            return this.nameTypeField;
        }
        set
        {
            this.nameTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.epri.com/2013/DERGroupDispatch#")]
public partial class NameType
{
    
    private string descriptionField;
    
    private string nameField;
    
    private NameTypeAuthority nameTypeAuthorityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public NameTypeAuthority NameTypeAuthority
    {
        get
        {
            return this.nameTypeAuthorityField;
        }
        set
        {
            this.nameTypeAuthorityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.epri.com/2013/DERGroupDispatch#")]
public partial class NameTypeAuthority
{
    
    private string descriptionField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.epri.com/2013/DERGroupDispatch#")]
public partial class RequestedCapability
{
    
    private capabilityType capabilityTypeField;
    
    private float valueField;
    
    private string capabilityUnitsField;
    
    private UnitMultiplier capabilityMultiplierField;
    
    public RequestedCapability()
    {
        this.capabilityUnitsField = "VA";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public capabilityType capabilityType
    {
        get
        {
            return this.capabilityTypeField;
        }
        set
        {
            this.capabilityTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public float value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string capabilityUnits
    {
        get
        {
            return this.capabilityUnitsField;
        }
        set
        {
            this.capabilityUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public UnitMultiplier capabilityMultiplier
    {
        get
        {
            return this.capabilityMultiplierField;
        }
        set
        {
            this.capabilityMultiplierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.epri.com/2013/DERGroupDispatch#")]
public enum capabilityType
{
    
    /// <remarks/>
    RealPower,
    
    /// <remarks/>
    ApparentPower,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.epri.com/2013/DERGroupDispatch#")]
public enum UnitMultiplier
{
    
    /// <remarks/>
    G,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    T,
    
    /// <remarks/>
    c,
    
    /// <remarks/>
    d,
    
    /// <remarks/>
    k,
    
    /// <remarks/>
    m,
    
    /// <remarks/>
    micro,
    
    /// <remarks/>
    n,
    
    /// <remarks/>
    none,
    
    /// <remarks/>
    p,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.epri.com/2013/DERGroupDispatch#")]
public partial class extensionsItem
{
    
    private string extNameField;
    
    private string extValueField;
    
    private string extTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string extName
    {
        get
        {
            return this.extNameField;
        }
        set
        {
            this.extNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string extValue
    {
        get
        {
            return this.extValueField;
        }
        set
        {
            this.extValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string extType
    {
        get
        {
            return this.extTypeField;
        }
        set
        {
            this.extTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.epri.com/2013/DERGroupDispatch#")]
public partial class otherCapability
{
    
    private string otherCapabilityTypeField;
    
    private string otherCapabilitySubTypeField;
    
    private float otherCapabilityValueField;
    
    private bool otherCapabilityValueFieldSpecified;
    
    private string otherCapabilityUnitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string otherCapabilityType
    {
        get
        {
            return this.otherCapabilityTypeField;
        }
        set
        {
            this.otherCapabilityTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string otherCapabilitySubType
    {
        get
        {
            return this.otherCapabilitySubTypeField;
        }
        set
        {
            this.otherCapabilitySubTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public float otherCapabilityValue
    {
        get
        {
            return this.otherCapabilityValueField;
        }
        set
        {
            this.otherCapabilityValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool otherCapabilityValueSpecified
    {
        get
        {
            return this.otherCapabilityValueFieldSpecified;
        }
        set
        {
            this.otherCapabilityValueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string otherCapabilityUnits
    {
        get
        {
            return this.otherCapabilityUnitsField;
        }
        set
        {
            this.otherCapabilityUnitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class OperationSet
{
    
    private bool enforceMsgSequenceField;
    
    private bool enforceMsgSequenceFieldSpecified;
    
    private bool enforceTransactionalIntegrityField;
    
    private bool enforceTransactionalIntegrityFieldSpecified;
    
    private OperationType[] operationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public bool enforceMsgSequence
    {
        get
        {
            return this.enforceMsgSequenceField;
        }
        set
        {
            this.enforceMsgSequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool enforceMsgSequenceSpecified
    {
        get
        {
            return this.enforceMsgSequenceFieldSpecified;
        }
        set
        {
            this.enforceMsgSequenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public bool enforceTransactionalIntegrity
    {
        get
        {
            return this.enforceTransactionalIntegrityField;
        }
        set
        {
            this.enforceTransactionalIntegrityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool enforceTransactionalIntegritySpecified
    {
        get
        {
            return this.enforceTransactionalIntegrityFieldSpecified;
        }
        set
        {
            this.enforceTransactionalIntegrityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Operation", Order=2)]
    public OperationType[] Operation
    {
        get
        {
            return this.operationField;
        }
        set
        {
            this.operationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class OperationType
{
    
    private string operationIdField;
    
    private string nounField;
    
    private string verbField;
    
    private bool elementOperationField;
    
    private System.Xml.XmlElement anyField;
    
    public OperationType()
    {
        this.elementOperationField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
    public string operationId
    {
        get
        {
            return this.operationIdField;
        }
        set
        {
            this.operationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string noun
    {
        get
        {
            return this.nounField;
        }
        set
        {
            this.nounField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string verb
    {
        get
        {
            return this.verbField;
        }
        set
        {
            this.verbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool elementOperation
    {
        get
        {
            return this.elementOperationField;
        }
        set
        {
            this.elementOperationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
    public System.Xml.XmlElement Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class OptionType
{
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class RequestType
{
    
    private System.DateTime startTimeField;
    
    private bool startTimeFieldSpecified;
    
    private System.DateTime endTimeField;
    
    private bool endTimeFieldSpecified;
    
    private OptionType[] optionField;
    
    private RequestTypeID[] idField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public System.DateTime StartTime
    {
        get
        {
            return this.startTimeField;
        }
        set
        {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StartTimeSpecified
    {
        get
        {
            return this.startTimeFieldSpecified;
        }
        set
        {
            this.startTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public System.DateTime EndTime
    {
        get
        {
            return this.endTimeField;
        }
        set
        {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndTimeSpecified
    {
        get
        {
            return this.endTimeFieldSpecified;
        }
        set
        {
            this.endTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Option", Order=2)]
    public OptionType[] Option
    {
        get
        {
            return this.optionField;
        }
        set
        {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ID", Order=3)]
    public RequestTypeID[] ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class RequestTypeID
{
    
    private string idTypeField;
    
    private string idAuthorityField;
    
    private IDKindType kindField;
    
    private bool kindFieldSpecified;
    
    private string objectTypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idType
    {
        get
        {
            return this.idTypeField;
        }
        set
        {
            this.idTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idAuthority
    {
        get
        {
            return this.idAuthorityField;
        }
        set
        {
            this.idAuthorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public IDKindType kind
    {
        get
        {
            return this.kindField;
        }
        set
        {
            this.kindField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool kindSpecified
    {
        get
        {
            return this.kindFieldSpecified;
        }
        set
        {
            this.kindFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string objectType
    {
        get
        {
            return this.objectTypeField;
        }
        set
        {
            this.objectTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class MessageProperty
{
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class UserType
{
    
    private string userIDField;
    
    private string organizationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string UserID
    {
        get
        {
            return this.userIDField;
        }
        set
        {
            this.userIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Organization
    {
        get
        {
            return this.organizationField;
        }
        set
        {
            this.organizationField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreateDERGroupDispatchRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage", Order=0)]
    public DERGroupDispatchRequestMessageType CreateDERGroupDispatch;
    
    public CreateDERGroupDispatchRequest()
    {
    }
    
    public CreateDERGroupDispatchRequest(DERGroupDispatchRequestMessageType CreateDERGroupDispatch)
    {
        this.CreateDERGroupDispatch = CreateDERGroupDispatch;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreateDERGroupDispatchResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage", Order=0)]
    public DERGroupDispatchResponseMessageType DERGroupDispatchResponseMessage;
    
    public CreateDERGroupDispatchResponse()
    {
    }
    
    public CreateDERGroupDispatchResponse(DERGroupDispatchResponseMessageType DERGroupDispatchResponseMessage)
    {
        this.DERGroupDispatchResponseMessage = DERGroupDispatchResponseMessage;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ChangeDERGroupDispatchRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage", Order=0)]
    public DERGroupDispatchRequestMessageType ChangeDERGroupDispatch;
    
    public ChangeDERGroupDispatchRequest()
    {
    }
    
    public ChangeDERGroupDispatchRequest(DERGroupDispatchRequestMessageType ChangeDERGroupDispatch)
    {
        this.ChangeDERGroupDispatch = ChangeDERGroupDispatch;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CancelDERGroupDispatchRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage", Order=0)]
    public DERGroupDispatchRequestMessageType CancelDERGroupDispatch;
    
    public CancelDERGroupDispatchRequest()
    {
    }
    
    public CancelDERGroupDispatchRequest(DERGroupDispatchRequestMessageType CancelDERGroupDispatch)
    {
        this.CancelDERGroupDispatch = CancelDERGroupDispatch;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CloseDERGroupDispatchRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage", Order=0)]
    public DERGroupDispatchRequestMessageType CloseDERGroupDispatch;
    
    public CloseDERGroupDispatchRequest()
    {
    }
    
    public CloseDERGroupDispatchRequest(DERGroupDispatchRequestMessageType CloseDERGroupDispatch)
    {
        this.CloseDERGroupDispatch = CloseDERGroupDispatch;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class DeleteDERGroupDispatchRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage", Order=0)]
    public DERGroupDispatchRequestMessageType DeleteDERGroupDispatch;
    
    public DeleteDERGroupDispatchRequest()
    {
    }
    
    public DeleteDERGroupDispatchRequest(DERGroupDispatchRequestMessageType DeleteDERGroupDispatch)
    {
        this.DeleteDERGroupDispatch = DeleteDERGroupDispatch;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface DERGroupDispatch_PortChannel : DERGroupDispatch_Port, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DERGroupDispatch_PortClient : System.ServiceModel.ClientBase<DERGroupDispatch_Port>, DERGroupDispatch_Port
{
    
    public DERGroupDispatch_PortClient()
    {
    }
    
    public DERGroupDispatch_PortClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DERGroupDispatch_PortClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DERGroupDispatch_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DERGroupDispatch_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreateDERGroupDispatchResponse DERGroupDispatch_Port.CreateDERGroupDispatch(CreateDERGroupDispatchRequest request)
    {
        return base.Channel.CreateDERGroupDispatch(request);
    }
    
    public DERGroupDispatchResponseMessageType CreateDERGroupDispatch(DERGroupDispatchRequestMessageType CreateDERGroupDispatch1)
    {
        CreateDERGroupDispatchRequest inValue = new CreateDERGroupDispatchRequest();
        inValue.CreateDERGroupDispatch = CreateDERGroupDispatch1;
        CreateDERGroupDispatchResponse retVal = ((DERGroupDispatch_Port)(this)).CreateDERGroupDispatch(inValue);
        return retVal.DERGroupDispatchResponseMessage;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> DERGroupDispatch_Port.CreateDERGroupDispatchAsync(CreateDERGroupDispatchRequest request)
    {
        return base.Channel.CreateDERGroupDispatchAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> CreateDERGroupDispatchAsync(DERGroupDispatchRequestMessageType CreateDERGroupDispatch)
    {
        CreateDERGroupDispatchRequest inValue = new CreateDERGroupDispatchRequest();
        inValue.CreateDERGroupDispatch = CreateDERGroupDispatch;
        return ((DERGroupDispatch_Port)(this)).CreateDERGroupDispatchAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreateDERGroupDispatchResponse DERGroupDispatch_Port.ChangeDERGroupDispatch(ChangeDERGroupDispatchRequest request)
    {
        return base.Channel.ChangeDERGroupDispatch(request);
    }
    
    public DERGroupDispatchResponseMessageType ChangeDERGroupDispatch(DERGroupDispatchRequestMessageType ChangeDERGroupDispatch1)
    {
        ChangeDERGroupDispatchRequest inValue = new ChangeDERGroupDispatchRequest();
        inValue.ChangeDERGroupDispatch = ChangeDERGroupDispatch1;
        CreateDERGroupDispatchResponse retVal = ((DERGroupDispatch_Port)(this)).ChangeDERGroupDispatch(inValue);
        return retVal.DERGroupDispatchResponseMessage;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> DERGroupDispatch_Port.ChangeDERGroupDispatchAsync(ChangeDERGroupDispatchRequest request)
    {
        return base.Channel.ChangeDERGroupDispatchAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> ChangeDERGroupDispatchAsync(DERGroupDispatchRequestMessageType ChangeDERGroupDispatch)
    {
        ChangeDERGroupDispatchRequest inValue = new ChangeDERGroupDispatchRequest();
        inValue.ChangeDERGroupDispatch = ChangeDERGroupDispatch;
        return ((DERGroupDispatch_Port)(this)).ChangeDERGroupDispatchAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreateDERGroupDispatchResponse DERGroupDispatch_Port.CancelDERGroupDispatch(CancelDERGroupDispatchRequest request)
    {
        return base.Channel.CancelDERGroupDispatch(request);
    }
    
    public DERGroupDispatchResponseMessageType CancelDERGroupDispatch(DERGroupDispatchRequestMessageType CancelDERGroupDispatch1)
    {
        CancelDERGroupDispatchRequest inValue = new CancelDERGroupDispatchRequest();
        inValue.CancelDERGroupDispatch = CancelDERGroupDispatch1;
        CreateDERGroupDispatchResponse retVal = ((DERGroupDispatch_Port)(this)).CancelDERGroupDispatch(inValue);
        return retVal.DERGroupDispatchResponseMessage;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> DERGroupDispatch_Port.CancelDERGroupDispatchAsync(CancelDERGroupDispatchRequest request)
    {
        return base.Channel.CancelDERGroupDispatchAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> CancelDERGroupDispatchAsync(DERGroupDispatchRequestMessageType CancelDERGroupDispatch)
    {
        CancelDERGroupDispatchRequest inValue = new CancelDERGroupDispatchRequest();
        inValue.CancelDERGroupDispatch = CancelDERGroupDispatch;
        return ((DERGroupDispatch_Port)(this)).CancelDERGroupDispatchAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreateDERGroupDispatchResponse DERGroupDispatch_Port.CloseDERGroupDispatch(CloseDERGroupDispatchRequest request)
    {
        return base.Channel.CloseDERGroupDispatch(request);
    }
    
    public DERGroupDispatchResponseMessageType CloseDERGroupDispatch(DERGroupDispatchRequestMessageType CloseDERGroupDispatch1)
    {
        CloseDERGroupDispatchRequest inValue = new CloseDERGroupDispatchRequest();
        inValue.CloseDERGroupDispatch = CloseDERGroupDispatch1;
        CreateDERGroupDispatchResponse retVal = ((DERGroupDispatch_Port)(this)).CloseDERGroupDispatch(inValue);
        return retVal.DERGroupDispatchResponseMessage;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> DERGroupDispatch_Port.CloseDERGroupDispatchAsync(CloseDERGroupDispatchRequest request)
    {
        return base.Channel.CloseDERGroupDispatchAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> CloseDERGroupDispatchAsync(DERGroupDispatchRequestMessageType CloseDERGroupDispatch)
    {
        CloseDERGroupDispatchRequest inValue = new CloseDERGroupDispatchRequest();
        inValue.CloseDERGroupDispatch = CloseDERGroupDispatch;
        return ((DERGroupDispatch_Port)(this)).CloseDERGroupDispatchAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreateDERGroupDispatchResponse DERGroupDispatch_Port.DeleteDERGroupDispatch(DeleteDERGroupDispatchRequest request)
    {
        return base.Channel.DeleteDERGroupDispatch(request);
    }
    
    public DERGroupDispatchResponseMessageType DeleteDERGroupDispatch(DERGroupDispatchRequestMessageType DeleteDERGroupDispatch1)
    {
        DeleteDERGroupDispatchRequest inValue = new DeleteDERGroupDispatchRequest();
        inValue.DeleteDERGroupDispatch = DeleteDERGroupDispatch1;
        CreateDERGroupDispatchResponse retVal = ((DERGroupDispatch_Port)(this)).DeleteDERGroupDispatch(inValue);
        return retVal.DERGroupDispatchResponseMessage;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> DERGroupDispatch_Port.DeleteDERGroupDispatchAsync(DeleteDERGroupDispatchRequest request)
    {
        return base.Channel.DeleteDERGroupDispatchAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateDERGroupDispatchResponse> DeleteDERGroupDispatchAsync(DERGroupDispatchRequestMessageType DeleteDERGroupDispatch)
    {
        DeleteDERGroupDispatchRequest inValue = new DeleteDERGroupDispatchRequest();
        inValue.DeleteDERGroupDispatch = DeleteDERGroupDispatch;
        return ((DERGroupDispatch_Port)(this)).DeleteDERGroupDispatchAsync(inValue);
    }
}
namespace iec.ch.TC57._2011.DERGroupDispatchMessage
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DERGroupDispatchFaultMessageType", Namespace="http://iec.ch/TC57/2011/DERGroupDispatchMessage")]
    public partial class DERGroupDispatchFaultMessageType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private iec.ch.TC57._2011.schema.message.ReplyType ReplyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public iec.ch.TC57._2011.schema.message.ReplyType Reply
        {
            get
            {
                return this.ReplyField;
            }
            set
            {
                this.ReplyField = value;
            }
        }
    }
}
namespace iec.ch.TC57._2011.schema.message
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class ReplyType : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ReplyType", "http://iec.ch/TC57/2011/schema/message");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ReplyType.ResultType", Namespace="http://iec.ch/TC57/2011/schema/message")]
        public enum ResultType : int
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OK = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PARTIAL = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            FAILED = 2,
        }
    }
}
