//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSConfig {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint MSMajorVersion {
            get {
                return ((uint)(this["MSMajorVersion"]));
            }
            set {
                this["MSMajorVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint MSMinorVersion {
            get {
                return ((uint)(this["MSMinorVersion"]));
            }
            set {
                this["MSMinorVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint MSBuild {
            get {
                return ((uint)(this["MSBuild"]));
            }
            set {
                this["MSBuild"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint MSBranch {
            get {
                return ((uint)(this["MSBranch"]));
            }
            set {
                this["MSBranch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RC")]
        public string MSBuildString {
            get {
                return ((string)(this["MSBuildString"]));
            }
            set {
                this["MSBuildString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestApp")]
        public string MSAppName {
            get {
                return ((string)(this["MSAppName"]));
            }
            set {
                this["MSAppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MSAppVersion {
            get {
                return ((string)(this["MSAppVersion"]));
            }
            set {
                this["MSAppVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestCo")]
        public string MSCompany {
            get {
                return ((string)(this["MSCompany"]));
            }
            set {
                this["MSCompany"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MSAuditID {
            get {
                return ((string)(this["MSAuditID"]));
            }
            set {
                this["MSAuditID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MSAuditPassword {
            get {
                return ((string)(this["MSAuditPassword"]));
            }
            set {
                this["MSAuditPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X35")]
        public string MSSystemID {
            get {
                return ((string)(this["MSSystemID"]));
            }
            set {
                this["MSSystemID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MSPassword {
            get {
                return ((string)(this["MSPassword"]));
            }
            set {
                this["MSPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other")]
        public string MSCodedNameType {
            get {
                return ((string)(this["MSCodedNameType"]));
            }
            set {
                this["MSCodedNameType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X1")]
        public string MSCodedValue {
            get {
                return ((string)(this["MSCodedValue"]));
            }
            set {
                this["MSCodedValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X2")]
        public string MSCodedNamePart {
            get {
                return ((string)(this["MSCodedNamePart"]));
            }
            set {
                this["MSCodedNamePart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MSCodedDescription {
            get {
                return ((string)(this["MSCodedDescription"]));
            }
            set {
                this["MSCodedDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Feet")]
        public string MSCSAuthNameOther {
            get {
                return ((string)(this["MSCSAuthNameOther"]));
            }
            set {
                this["MSCSAuthNameOther"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auth1")]
        public string MSCSAuthNameValue {
            get {
                return ((string)(this["MSCSAuthNameValue"]));
            }
            set {
                this["MSCSAuthNameValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MSCSUnitOther {
            get {
                return ((string)(this["MSCSUnitOther"]));
            }
            set {
                this["MSCSUnitOther"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Feet")]
        public string MSCSUnitValue {
            get {
                return ((string)(this["MSCSUnitValue"]));
            }
            set {
                this["MSCSUnitValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A7")]
        public string MSCSDatum {
            get {
                return ((string)(this["MSCSDatum"]));
            }
            set {
                this["MSCSDatum"] = value;
            }
        }
    }
}
